using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace PythonIntegration
{
    public class Python
    {
        private static string PythonPath = "C:\\Python310\\python.exe";
        public static PythonResult Run(string cmd, List<string> args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = PythonPath;
            string arguments = $"\"{cmd}\"";
            foreach (var arg in args) arguments = arguments + $" \"{arg}\"";
            start.Arguments = arguments;
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            Process process = Process.Start(start);

            string result = process.StandardOutput.ReadToEnd();
            string error = process.StandardError.ReadToEnd();

            process.WaitForExit();

            return error == "" ? new PythonResult(result, true) : new PythonResult(error, false);
        }
    }
}
